spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: "{cipher}AYCPQJaYANUvzQlCevQGlHF9dEGM7uWiV6rHIHh5vF9teSb7fb1kvv7XIeR+ev6nMNl1TMhS61BuxELKsauvV1rudJzZKg9RNSk9OCe5/nvXrF9sWfLbrfurxEqoQ/o0gjKt5X5LhLvHXlUXd3ieL1GvM8rCKXiXrC5QNzs0nkBM26uorh6AS++WojHDZv1WxuBlDENf9CvH1BC2isSA0HSsPXQF8FUvkSzu8TecQsv9E3x19fY5BKrvUnixNHGZbCxQZo/mDlGQqw8YxxJ+wJZa8LmAdNezmwTjujktMUKF7WJxaddpMsdp3lKRNHPk3yF/JuxoSuWbPDhsDbhN8K/246Im7JwM1XKltRbW75tl1SU50rZcvW9YRgK+Kk1127n4h9ZF6hgYSR7LuUiTzx08yE710q3XB+dGm+rEXvomu1UmJbj78lzBQn7P/vqfgHz2uh3ZfVP0Pg0qQ5mRyqz0CQUEyfoOPZnGdsPTF/r8UN9HMC4ifSYdNpAAltg3ClG7AVBofs8He33l3kOc7t6Vq805wUeAcuQ0KtcpVH0mhA=="

token:
  expiration_time: 86400000
  secret: "{cipher}AYAw/aOxc8S5jSeIpVrku7x4BHDpAE0ELNqe+BvCkx3SndLo+uOl3VaPqqFz4RJdGGjCjTde3F1KZRTFNfOYpBQunkqnyCvwsZigJ4Qx9NIloJU2SaizwQFQVf5BV/KfXemSSPPi4F+nQIz2cDEgbCx3+RQmsNAmHeFJ4vtBTS8cFWFe+YUJWYOUR0KVRU+xDUceFXSMfIKFZ7OI491EKDJmxxYmRw5rro0jpfkYCjeyspNHWn533AETShlGox6gaCcwn+suv5y+K+u7lRKrjBMmwsdHNywNS1OsYnAOk/YXSIHlQmjJxP6UoLQXMDdOy6HvxhBRfNd24ZEMOmeUsYexTCbxLziJdFufX/h+heeVrORUjSzUBJ8ebZB1X2jpQ+WDU6M891mK35AMJx5c6In2zMpSEmsTX6KtYdGrwZRerod/Vp0T5Zz9luz7HmKBmwPuq2q+UoaSYers2ueCTzspgTxv4olxfMXbmIB/nzHvhRlVwWUlHicFC0rnWLtHLjnIOvDkCB87Z7IFsLsikX6H6IgocLQipII5OikPzmq3ltnPD+y4vZOo9EgOunDN3DehCG7uyFIjHCIvufb6EaWO"

gateway:
  ip: 172.30.1.68

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
